### ISSUE TITLE
Using `cssVariables.json` and `themeConfig.json`

### ISSUE THREAD

**Issue by samikeijonen** [wprig/wprig#247]
I have a question using `cssVariables.json`. Would it be neat that it would be the only place where you set your variables?

For example `--large-font-size` is set in `cssVariables.json` but then you set it again in `add_theme_support( 'editor-font-sizes' )`.

I'm trying to vision that we could use variables from single location in CSS, PHP, JS, design systems, you name it.

Also if I set `convertCSSVariables: false` in `themeConfig.json`, which set's `preserve: true` in `postcssCustomMedia`, CSS variables doesn't work anymore.

Example:

```css
.entry-content > * {
    max-width: 45rem;
    max-width: var(--content-width) rem; // there is empty char for some reason before rem
}
```
`max-width: var(--content-width)rem` doesn't apply now for modern browsers since we don't have those variables in CSS/SASS. Can those variables be imported somehow in the same time for be used in CSS?

I don't have answer to these issues, but I know someone do:)
