### ISSUE TITLE
Reduce calc usage when possible

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#378]
## Issue Overview

With custom properties, it's tempting to add many variables, like one to use as a spacing unit. This kind of usage will imply to frequently use `calc()` in the stylesheets. It would be nice if the build process could reduce their usage by processing the value whenever it's possible, to simplify the work for the browser.

This could be done by the [PostCSS Calc](https://github.com/postcss/postcss-calc) plugin. When multiple units are mixed together in the same expression, the `calc()` statement is left as is, to fallback to the W3C calc() implementation.

Cc. @ataylorme for feedback

**Comment by ataylorme** [comment]
@benoitchantre this looks like a good improvement, thank you for surfacing it. The implementation seems straight-forward but I would like to wait for #369 to be merged before opening a pull request for this.

**Comment by benoitchantre** [comment]
> I would like to wait for #369

No problem. Thank you for including this in `v2.0`

**Comment by ataylorme** [comment]
@mor10 one question is do we want `preserve` to be `true` or `false` for the `calc()` PostCSS plugin. Here is an example

Source:
```css
.foo {
	padding: calc((100vw - 50em) / 2);
	margin: calc(100px - (100px - 100%));
}

:root {
  --main-font-size: 16px;
}

body {
  font-size: var(--main-font-size);
}

h1 {
  font-size: calc(var(--main-font-size) * 2);
  height: calc(100px - 2em);
  margin-bottom: calc(
      var(--main-font-size)
      * 1.5
    )
}
```

`preserve: false`:
```css
.foo {
	padding: calc((100vw - 50em)/2);
	margin: 100%;
}

:root {
	--main-font-size: 16px;
}

body {
	font-size: 16px;
	font-size: var(--main-font-size);
}

h1 {
	font-size: 32px;
	font-size: calc(var(--main-font-size)*2);
	height: calc(100px - 2em);
	margin-bottom: 24px;
	margin-bottom: calc(var(--main-font-size)*1.5)
}
```

`preserve: true`:
```css
.foo {
	padding: calc((100vw - 50em)/2);
	padding: calc((100vw - 50em) / 2);
	margin: 100%;
	margin: calc(100px - (100px - 100%));
}

:root {
	--main-font-size: 16px;
}

body {
	font-size: 16px;
	font-size: var(--main-font-size);
}

h1 {
	font-size: 32px;
	font-size: calc(16px * 2);
	font-size: calc(var(--main-font-size)*2);
	font-size: calc(var(--main-font-size) * 2);
	height: calc(100px - 2em);
	margin-bottom: 24px;
	margin-bottom: calc(
			16px
			* 1.5
		);
	margin-bottom: calc(var(--main-font-size)*1.5);
	margin-bottom: calc(
			var(--main-font-size)
			* 1.5
		)
}
```
