### ISSUE TITLE
Missing gutter between columns

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#496]
## Issue Overview

There's no gutter between columns. When columns contain text, it makes the text very hard to read.

## Expected Behavior

Columns should be separated by some white space.

## Possible Solution

Remove the following selectors. The front-end stylesheet of the block editor sets gutters.

```css
.wp-block-column:not(:last-child),
.wp-block-column:nth-child(2n+1) {
	margin-right: 0;
}

.wp-block-column:not(:first-child) {
	margin-left: 0;
}
```
## Screenshots / Video

<img width="784" alt="Capture d’écran 2019-05-28 à 21 26 43" src="https://user-images.githubusercontent.com/1521015/58506311-50f43980-818f-11e9-85fd-b4bfea799b73.png">
