### ISSUE TITLE
Insufficient z-index value for sub menus

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#521]
## Issue Overview

When the first block is a cover block, sub menus may be displayed below the content of the cover block.

From the block library stylesheet
```css
.wp-block-cover-image .wp-block-cover__inner-container, .wp-block-cover .wp-block-cover__inner-container {
    z-index: 1;

}
``` 

In global.css
```css
.nav--toggle-sub ul ul {
    z-index: 1;

}
```

## Possible Solution

Increase the `z-index` value for sub menus (`.nav--toggle-sub ul ul`) to an higher value.
