### ISSUE TITLE
Remove unnecessary selectors for links inside blocks with a custom color

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#613]
## Issue Overview

There's no need to define explicitly the color of the link when there's a custom block color.

https://github.com/wprig/wprig/blob/e9b189b761a23ade041d2a054738a86043387e14/assets/css/src/content.css#L178

This is alredy done by the Block Editor stylesheet with the following selector:

```css
p.has-text-color a {
  color: inherit;
}
```
